-- MySQL Script generated by MySQL Workbench
-- Sun Jun 10 17:58:24 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema formulario
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema formulario
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `formulario` DEFAULT CHARACTER SET utf8 ;
USE `formulario` ;

-- -----------------------------------------------------
-- Table `formulario`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `formulario`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NULL,
  `correo` VARCHAR(50) NULL,
  `contrasena` VARCHAR(75) NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `formulario`.`fotos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `formulario`.`fotos` (
  `idfotos` INT NOT NULL AUTO_INCREMENT,
  `ruta` VARCHAR(100) NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idfotos`),
  INDEX `fk_fotos_usuario_idx` (`usuario_idusuario` ASC),
  CONSTRAINT `fk_fotos_usuario`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `formulario`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
